/*
 *  Script generated by LS Script Generator, v.TK.0
 *
 *  For download info, please visit:
 *  http://nwvault.ign.com/View.php?view=Other.Detail&id=1502
 */
// Put this script OnClose.


void main()
{
    object oTarget;

    // Get the creature who triggered this event.
    object oPC = GetLastClosedBy();

    // Give "stone" to "ds_plc_rubble4".
    oTarget = GetObjectByTag("ds_plc_rubble4");
    CreateItemOnObject("stone", oTarget);
}
