/*
 *  Script generated by LS Script Generator, v.TK.0
 *
 *  For download info, please visit:
 *  http://nwvault.ign.com/View.php?view=Other.Detail&id=1502
 */
// Put this script OnDeath.


void main()
{
    // Get the creature who triggered this event.
    object oPC = GetLastKiller();

    // Make us like the PC more.
    AdjustReputation(oPC, OBJECT_SELF, 100);
}

